### ISSUE TITLE
IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by cazzap** [Zaarrg/comet-uncached#4]
Error:
----------------
File "/app/comet/api/stream.py", line 351
del torrents[filtered[0] - index_less]

IndexError: list assignment index out of range

Issue:
----------------
Crashes when parsing certain titles from Zilean while "TITLE_MATCH_CHECK=True"

Example:
----------------------
Happens when it checks "The Equalizer" movie from Zilean.
This is the first result from zilean in the list:

[
  {
    "raw_title": "the equalizer 2021 s02e01 internal 1080p web h264-whosnext[eztv re] mkv",
    "parsed_title": "the equalizer",
    "normalized_title": "the equalizer",
   ..
   ..
   "category": "tvSeries",

Im guessing its an issue with zilean returning "The Equalizer" tv series as the first result instead of the movie?

**Comment by Zaarrg** [comment]
This should now be fixed in the latest commit. 
Would appreciate if you could test and confirm that.

**Comment by cazzap** [comment]
Tested with 4 different titles and no issues found. Thank you

**Comment by Zaarrg** [comment]
nice, thnx for reporting the bug
